import XCTest
@testable import ToolBoxCore

final class ClipboardCoordinatorTests: XCTestCase {
    var coordinator: ClipboardCoordinator!
    var store: ClipboardStore!

    @MainActor
    override func setUp() {
        super.setUp()
        store = ClipboardStore()
        coordinator = ClipboardCoordinator(store: store)
    }

    @MainActor
    override func tearDown() {
        coordinator.stop()
        coordinator = nil
        store = nil
        // Coordinator tests write persistence keys; never leak them into the
        // host app's real defaults.
        UserDefaults.standard.removeObject(forKey: "clipboard.retentionSeconds")
        UserDefaults.standard.removeObject(forKey: "clipboard.memoryLimitBytes")
        super.tearDown()
    }

    @MainActor
    func testStartStop() {
        coordinator.start()
        // Timer should be running (no direct way to test, but shouldn't crash)

        coordinator.stop()
        // Timer should be stopped
    }

    @MainActor
    func testMemoryLimitConfiguration() {
        coordinator.memoryLimit = 1024
        coordinator.timeLimit = 7200

        // Should propagate to store (verify indirectly through behavior)
        XCTAssertNotNil(coordinator)
    }

    @MainActor
    func testSensitiveTypeMarkers() {
        let markers = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType",
            "de.petermaurer.TransientPasteboardType",
            "com.typeit4me.clipping",
            "Pasteboard generator type",
            "com.apple.is-remote-clipboard",
            "com.agilebits.onepassword.NSPasteboardItem",
        ]
        for marker in markers {
            XCTAssertTrue(
                ClipboardCoordinator.isSensitiveType(NSPasteboard.PasteboardType(marker)),
                "expected \(marker) to be filtered"
            )
        }

        XCTAssertFalse(ClipboardCoordinator.isSensitiveType(.string))
        XCTAssertFalse(ClipboardCoordinator.isSensitiveType(.png))
        XCTAssertFalse(
            ClipboardCoordinator.isSensitiveType(
                NSPasteboard.PasteboardType("com.apple.iWork.TSPNativeMetadata")
            )
        )
    }

    @MainActor
    func testMonitoringFlagGatesPanel() {
        XCTAssertFalse(coordinator.isMonitoring)

        // Disabled feature must not capture nor present the panel.
        coordinator.showPanel()
        XCTAssertNil(coordinator.panelController)

        coordinator.start()
        XCTAssertTrue(coordinator.isMonitoring)
        coordinator.stop()
        XCTAssertFalse(coordinator.isMonitoring)
    }

    @MainActor
    func testStopClosesPresentedPanel() {
        coordinator.start()
        coordinator.showPanel()
        let controller = coordinator.panelController
        XCTAssertNotNil(controller)

        coordinator.stop()

        XCTAssertFalse(controller?.window?.isVisible ?? true)
    }

    @MainActor
    func testSettingsPersistAcrossInstances() {
        UserDefaults.standard.removeObject(forKey: "clipboard.retentionSeconds")
        UserDefaults.standard.removeObject(forKey: "clipboard.memoryLimitBytes")
        defer {
            UserDefaults.standard.removeObject(forKey: "clipboard.retentionSeconds")
            UserDefaults.standard.removeObject(forKey: "clipboard.memoryLimitBytes")
        }

        coordinator.timeLimit = 3600
        coordinator.memoryLimit = 20 * 1024 * 1024

        let fresh = ClipboardCoordinator(store: ClipboardStore())
        XCTAssertEqual(fresh.timeLimit, 3600)
        XCTAssertEqual(fresh.memoryLimit, 20 * 1024 * 1024)
    }

    @MainActor
    func testStoreChangesForwardCoordinatorObjectWillChange() {
        var fired = false
        let cancellable = coordinator.objectWillChange.sink { _ in fired = true }

        store.addOrUpdate(hash: "fwd", text: "x", image: nil, types: [.string])

        // Forwarding hops through a Task on the main actor; pump the run loop.
        let exp = expectation(description: "objectWillChange forwarded")
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) { exp.fulfill() }
        wait(for: [exp], timeout: 3)

        XCTAssertTrue(fired)
        _ = cancellable
    }

    @MainActor
    func testAccessors() {
        XCTAssertEqual(coordinator.memoryUsage, 0)
        XCTAssertEqual(coordinator.itemCount, 0)

        // Add item directly to store
        store.addOrUpdate(hash: "test", text: "content", image: nil, types: [.string])

        XCTAssertGreaterThan(coordinator.memoryUsage, 0)
        XCTAssertEqual(coordinator.itemCount, 1)
    }
}

final class ClipboardItemTests: XCTestCase {
    func testComputeHashText() {
        let hash1 = ClipboardItem.computeHash(text: "Hello", image: nil)
        let hash2 = ClipboardItem.computeHash(text: "Hello", image: nil)
        let hash3 = ClipboardItem.computeHash(text: "World", image: nil)

        // Same content should produce same hash
        XCTAssertEqual(hash1, hash2)

        // Different content should produce different hash
        XCTAssertNotEqual(hash1, hash3)

        // SHA-256 produces 64 hex characters
        XCTAssertEqual(hash1.count, 64)
    }

    func testComputeHashImage() {
        let data1 = Data([0x01, 0x02, 0x03])
        let data2 = Data([0x01, 0x02, 0x03])
        let data3 = Data([0x04, 0x05, 0x06])

        let hash1 = ClipboardItem.computeHash(text: nil, image: data1)
        let hash2 = ClipboardItem.computeHash(text: nil, image: data2)
        let hash3 = ClipboardItem.computeHash(text: nil, image: data3)

        XCTAssertEqual(hash1, hash2)
        XCTAssertNotEqual(hash1, hash3)
    }

    func testComputeHashCombined() {
        let text = "Text"
        let image = Data([0x01])

        let hashTextOnly = ClipboardItem.computeHash(text: text, image: nil)
        let hashImageOnly = ClipboardItem.computeHash(text: nil, image: image)
        let hashBoth = ClipboardItem.computeHash(text: text, image: image)

        // Combined hash should be different from individual hashes
        XCTAssertNotEqual(hashBoth, hashTextOnly)
        XCTAssertNotEqual(hashBoth, hashImageOnly)
    }

    func testComputeHashSeparatesTextFromImage() {
        // Same bytes, different kind: must not collide (previously "abc" text
        // and "abc" image produced identical hashes).
        let textHash = ClipboardItem.computeHash(text: "abc", image: nil)
        let imageHash = ClipboardItem.computeHash(text: nil, image: Data("abc".utf8))
        XCTAssertNotEqual(textHash, imageHash)
    }

    func testComputeHashSeparatesPartBoundaries() {
        // Shifted concatenations of the same total bytes must differ.
        let shiftedA = ClipboardItem.computeHash(text: "ab", image: Data("c".utf8))
        let shiftedB = ClipboardItem.computeHash(text: "a", image: Data("bc".utf8))
        XCTAssertNotEqual(shiftedA, shiftedB)
    }

    func testImageTypeStoredOnItem() {
        let item = ClipboardItem(
            contentHash: "img",
            types: [.tiff],
            textContent: nil,
            imageData: Data([0x49, 0x49, 0x2A, 0x00]),
            imageType: .tiff
        )
        XCTAssertEqual(item.imageType, .tiff)
    }

    func testImageTypeSniffedWhenOmitted() {
        // TIFF bytes stored without an explicit type must not fall back to a
        // false .png declaration on write-back.
        let tiffBytes = Data([0x49, 0x49, 0x2A, 0x00, 0, 0, 0, 0])
        let tiffItem = ClipboardItem(contentHash: "t", types: [.tiff], textContent: nil, imageData: tiffBytes)
        XCTAssertEqual(tiffItem.imageType, .tiff)

        let pngBytes = Data([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])
        let pngItem = ClipboardItem(contentHash: "p", types: [.png], textContent: nil, imageData: pngBytes)
        XCTAssertEqual(pngItem.imageType, .png)

        // Unknown bytes carry no type claim instead of a false .png.
        let unknownItem = ClipboardItem(
            contentHash: "u",
            types: [],
            textContent: nil,
            imageData: Data([0x00, 0x01, 0x02, 0x03])
        )
        XCTAssertNil(unknownItem.imageType)

        // Text-only items never carry an image type.
        let textItem = ClipboardItem(
            contentHash: "x",
            types: [.string],
            textContent: "hi",
            imageData: nil,
            imageType: .tiff
        )
        XCTAssertNil(textItem.imageType)
    }

    func testEstimatedSize() {
        let item = ClipboardItem(
            contentHash: "abc123",
            types: [.string],
            textContent: "Hello",
            imageData: nil
        )

        // Should have non-zero size
        XCTAssertGreaterThan(item.estimatedSize, 0)

        let itemWithImage = ClipboardItem(
            contentHash: "def456",
            types: [.png],
            textContent: nil,
            imageData: Data(count: 1000)
        )

        // Item with image should be larger
        XCTAssertGreaterThan(itemWithImage.estimatedSize, item.estimatedSize)
    }

    func testIsImage() {
        let textItem = ClipboardItem(
            contentHash: "text",
            types: [.string],
            textContent: "Hello",
            imageData: nil
        )

        let imageItem = ClipboardItem(
            contentHash: "image",
            types: [.png],
            textContent: nil,
            imageData: Data([0x01])
        )

        XCTAssertFalse(textItem.isImage)
        XCTAssertTrue(imageItem.isImage)
    }
}

@MainActor
final class ClipboardPanelModelTests: XCTestCase {
    func testSearchExcludesImagesAndIsCaseInsensitive() {
        let store = ClipboardStore()
        store.addOrUpdate(hash: "text", text: "Hello Clipboard", image: nil, types: [.string])
        store.addOrUpdate(hash: "image", text: nil, image: Data([1, 2]), types: [.png])
        let model = ClipboardPanelModel(store: store)

        model.query = "CLIP"
        XCTAssertEqual(model.filteredItems.map(\.contentHash), ["text"])
    }

    func testSelectionWraps() {
        let store = ClipboardStore()
        store.addOrUpdate(hash: "one", text: "1", image: nil, types: [.string])
        store.addOrUpdate(hash: "two", text: "2", image: nil, types: [.string])
        let model = ClipboardPanelModel(store: store)
        model.selectFirst()

        model.moveSelection(by: -1)
        XCTAssertEqual(model.selectedItem?.contentHash, "one")
        model.moveSelection(by: 1)
        XCTAssertEqual(model.selectedItem?.contentHash, "two")
    }

    func testSelectionTracksItemIdentityAcrossHeadInsert() {
        let store = ClipboardStore()
        store.addOrUpdate(hash: "one", text: "1", image: nil, types: [.string])
        store.addOrUpdate(hash: "two", text: "2", image: nil, types: [.string])
        let model = ClipboardPanelModel(store: store)
        model.selectFirst()
        XCTAssertEqual(model.selectedItem?.contentHash, "two")

        // Monitoring inserts a newer item at the head; the user's selection
        // must stay on the same content, not the same index.
        store.addOrUpdate(hash: "three", text: "3", image: nil, types: [.string])

        XCTAssertEqual(model.selectedItem?.contentHash, "two")
        XCTAssertEqual(model.selectedIndex, 1)
    }

    func testSelectionFollowsIdentityWhileFiltering() {
        let store = ClipboardStore()
        store.addOrUpdate(hash: "one", text: "apple", image: nil, types: [.string])
        store.addOrUpdate(hash: "two", text: "banana", image: nil, types: [.string])
        let model = ClipboardPanelModel(store: store)
        model.selectFirst() // "banana"

        // Tracked item filtered out -> fall back to the first visible row.
        model.query = "app"
        XCTAssertEqual(model.selectedItem?.contentHash, "one")

        // Full list restored -> tracked item "one" is still visible, stays selected.
        model.query = ""
        XCTAssertEqual(model.selectedItem?.contentHash, "one")
        XCTAssertEqual(model.selectedIndex, 1)
    }
}
